name: sync_rules
on: [push, pull_request] # Trigger the workflow on push or pull request
jobs:
  diff-pr:
    runs-on: ubuntu-latest
    steps:
      - name: diff-rules
        uses: grafana//cortex-rules-action@master
        with:
          rules_dir_path: "rules/"
          endpoint: https://dev-us-central1.grafana.net/api/prom
          instance_id: 5842
          action: diff
