name: sync_rules
on: [push, pull_request] # Trigger the workflow on push or pull request
jobs:
  diff-pr:
    runs-on: ubuntu-latest
    steps:
      - name: diff-rules
        uses: grafana//cortex-rules-action@master
        env:
          CORTEX_ADDRESS: https://dev-us-central1.grafana.net/api/prom
          CORTEX_TENANT_ID: 5842
          CORTEX_API_KEY: ${{ secrets.cortex_api_key }}
          ACTION: diff
          RULES_DIR: "./rules/"